import {
  Tenant,
  User,
  Judge,
  Competition,
  Submission,
  Photo,
  WinnerRecord,
  Article,
  AppNotification,
} from './types';
import { DEFAULT_SCORING_CRITERIA } from './constants';

export const MOCK_TENANTS: Tenant[] = [
  {
    id: 'tenant-pixel-prize',
    name: 'Pixel-Prize Official',
    slug: 'pixel-prize',
    logo: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=150&q=80',
    description: 'The global benchmark in modern competitive fine art, nature, and documentary photography.',
    website: 'https://pixelprize.io',
    verified: true,
    competitionCount: 18,
  },
  {
    id: 'tenant-nat-photo-club',
    name: 'National Photography Club',
    slug: 'national-photo-club',
    logo: 'https://images.unsplash.com/photo-1502982720700-bfff97f2da6d?auto=format&fit=crop&w=150&q=80',
    description: 'Uniting passionate visual storytellers and landscape preservationists worldwide.',
    website: 'https://nationalphotoclub.org',
    verified: true,
    competitionCount: 8,
  },
  {
    id: 'tenant-creative-lens',
    name: 'Creative Lens Society',
    slug: 'creative-lens',
    logo: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=150&q=80',
    description: 'Exploring bold avant-garde perspectives, street culture, and abstract visual arts.',
    website: 'https://creativelens.art',
    verified: true,
    competitionCount: 6,
  },
  {
    id: 'tenant-wildlife-alliance',
    name: 'Global Wildlife Alliance',
    slug: 'wildlife-alliance',
    logo: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=150&q=80',
    description: 'Dedicated to wildlife conservation awareness through powerful animal imagery.',
    website: 'https://wildlifealliance.org',
    verified: true,
    competitionCount: 4,
  },
];

export const CURRENT_USER: User = {
  id: 'usr-alex-rivera',
  name: 'Alex Rivera',
  email: 'alex.rivera@lenscraft.io',
  role: 'user',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  bio: 'Visual artist and wilderness photographer captivated by natural light dynamics and endangered animal behaviors across the Pacific Northwest.',
  location: 'Seattle, Washington, USA',
  specialty: ['Wildlife', 'Landscape', 'Aerial Drone'],
  portfolioUrl: 'https://alexrivera.photo',
  instagram: '@alexrivera_raw',
  joinedDate: '2024-03-15',
  stats: {
    competitionsEntered: 6,
    submissionsCount: 6,
    shortlistsCount: 4,
    winsCount: 2,
  },
  cameraGear: {
    body: 'Sony Alpha 1 & Hasselblad X2D 100C',
    favoriteLens: 'Sony FE 400mm f/2.8 GM OSS',
  },
};

export const MOCK_JUDGES: Judge[] = [
  {
    id: 'jdg-elena-rostova',
    name: 'Elena Rostova',
    email: 'elena.rostova@jurypanel.org',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    title: 'Senior Juror & Former National Geographic Photo Editor',
    bio: 'Over 20 years evaluating global documentary and wildlife photography. Known for rigorous technical scrutiny and emotive framing appraisal.',
    expertise: ['Wildlife & Animals', 'Nature & Conservation', 'Photojournalism'],
    assignedCompetitionIds: ['comp-wildlife-2026', 'comp-nature-lens-2026'],
    reviewsCompleted: 42,
    totalAssignedReviews: 48,
    status: 'active',
    rating: 4.95,
    joinedDate: '2023-01-10',
  },
  {
    id: 'jdg-marcus-vance',
    name: 'Marcus Vance',
    email: 'marcus.vance@urbanframe.co',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    title: 'Architectural Photographer & Magnum Photos Contributor',
    bio: 'Specialist in high-contrast urban geometry, street narratives, and brutalist architecture with exhibitions in London, Tokyo, and Berlin.',
    expertise: ['Urban & Architecture', 'Street Photography', 'Monochrome'],
    assignedCompetitionIds: ['comp-urban-stories-2026', 'comp-monochrome-2026'],
    reviewsCompleted: 35,
    totalAssignedReviews: 40,
    status: 'active',
    rating: 4.88,
    joinedDate: '2023-04-18',
  },
  {
    id: 'jdg-sofia-chen',
    name: 'Sofia Chen',
    email: 'sofia.chen@voguecreative.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    title: 'Fashion & Fine Art Portrait Director',
    bio: 'Pioneering emotive lighting techniques and experimental editorial aesthetics for international fashion houses and gallery collections.',
    expertise: ['Portrait & People', 'Fine Art & Abstract', 'Studio Lighting'],
    assignedCompetitionIds: ['comp-portrait-masters-2026'],
    reviewsCompleted: 18,
    totalAssignedReviews: 24,
    status: 'busy',
    rating: 4.92,
    joinedDate: '2023-09-01',
  },
  {
    id: 'jdg-david-karanja',
    name: 'David Karanja',
    email: 'david.karanja@wildvision.ke',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    title: 'East African Wildlife Conservation Photographer',
    bio: 'Passionate advocate for anti-poaching initiatives and predator tracking in the Masai Mara and Serengeti ecosystems.',
    expertise: ['Wildlife & Animals', 'Aerial & Drone'],
    assignedCompetitionIds: ['comp-wildlife-2026'],
    reviewsCompleted: 28,
    totalAssignedReviews: 30,
    status: 'active',
    rating: 4.97,
    joinedDate: '2024-01-15',
  },
];

export const MOCK_COMPETITIONS: Competition[] = [
  {
    id: 'comp-wildlife-2026',
    tenantId: 'tenant-wildlife-alliance',
    tenantName: 'Global Wildlife Alliance',
    tenantLogo: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=150&q=80',
    title: 'Wildlife Photography Awards 2026',
    slug: 'wildlife-photography-awards-2026',
    category: 'Wildlife & Animals',
    shortDescription: 'Showcase rare encounters, raw predator instincts, and the fragile majesty of animal kingdoms worldwide.',
    description: 'The premier annual competition celebrating authentic wildlife behavior, raw habitats, and urgent conservation narratives. Our AI evaluation engine filters entries for technical excellence, focus precision, and exposure before our esteemed panel of international jurors conducts the final scoring.',
    coverImage: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?auto=format&fit=crop&w=1200&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=1600&q=80',
    status: 'active',
    prizePool: '$15,000 USD',
    totalPrizeValue: 15000,
    prizes: [
      {
        rank: '1st_place',
        title: 'Grand Winner & Golden Shutter Trophy',
        cashAmount: 8000,
        perks: ['Published in Annual Anthology', 'Solo Gallery Exhibition Feature', 'Pro Camera Gear Bundle ($2,500 value)', '1-Year Global Ambassador Membership'],
      },
      {
        rank: '2nd_place',
        title: 'Silver Runner-Up',
        cashAmount: 4500,
        perks: ['Full Feature in Pixel-Prize Magazine', 'Lens voucher ($1,000)', 'Commemorative Silver Plaque'],
      },
      {
        rank: '3rd_place',
        title: 'Bronze Finalist',
        cashAmount: 2500,
        perks: ['Official Certificate of Mastery', 'Annual platform Pro tier subscription'],
      },
    ],
    timeline: {
      registrationOpen: '2026-06-01T00:00:00Z',
      submissionDeadline: '2026-09-30T23:59:59Z',
      aiEvaluationComplete: '2026-10-05T00:00:00Z',
      judgingDeadline: '2026-10-20T00:00:00Z',
      resultsAnnouncement: '2026-10-25T18:00:00Z',
    },
    guidelines: {
      maxFileSizeMB: 35,
      allowedFormats: ['JPG', 'JPEG', 'TIFF', 'PNG'],
      minResolution: '3000 x 2000 px (300 DPI)',
      maxSubmissionsPerUser: 1,
      rules: [
        'Strictly 1 submission per photographer for this contest.',
        'Photographs must depict wild animals in their natural habitats (captive or baited animals are disqualified).',
        'Digital manipulation that alters the authenticity of wildlife behavior is strictly prohibited.',
        'EXIF metadata must remain intact in the uploaded file.',
        'Entries must have been captured within the last 24 months.',
      ],
      eligibility: [
        'Open to photographers of all experience levels globally.',
        'Must own 100% original copyright to the submitted photograph.',
        'Entrants must be at least 18 years of age at the time of submission.',
      ],
    },
    criteria: DEFAULT_SCORING_CRITERIA,
    submissionCount: 1420,
    judgeIds: ['jdg-elena-rostova', 'jdg-david-karanja'],
    featured: true,
    sponsor: 'Alpha Optics & Terra Conservation',
  },
  {
    id: 'comp-urban-stories-2026',
    tenantId: 'tenant-creative-lens',
    tenantName: 'Creative Lens Society',
    tenantLogo: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=150&q=80',
    title: 'Urban Stories & Street Challenge',
    slug: 'urban-stories-challenge-2026',
    category: 'Urban & Architecture',
    shortDescription: 'Document the pulse of cities, neon nights, geometric shadows, and human moments on the pavement.',
    description: 'A global stage for urban explorers and street visualists. From dizzying skyscraper reflections to candid subway interactions, uncover the stories living in the asphalt jungle.',
    coverImage: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1200&q=80',
    status: 'active',
    prizePool: '$10,000 USD',
    totalPrizeValue: 10000,
    prizes: [
      {
        rank: '1st_place',
        title: 'Metropolis Master Award',
        cashAmount: 6000,
        perks: ['Solo Billboard Feature in Downtown Tokyo', 'Leica Street Lens Kit', 'Global Press Release'],
      },
      {
        rank: '2nd_place',
        title: 'Urban Visionary',
        cashAmount: 2500,
        perks: ['Spotlight Editorial Interview', 'Printed Hardcover Monograph'],
      },
      {
        rank: '3rd_place',
        title: 'City Storyteller Finalist',
        cashAmount: 1500,
        perks: ['Framed Exhibition Print', 'Pro Platform Membership'],
      },
    ],
    timeline: {
      registrationOpen: '2026-07-01T00:00:00Z',
      submissionDeadline: '2026-10-15T23:59:59Z',
      aiEvaluationComplete: '2026-10-20T00:00:00Z',
      judgingDeadline: '2026-11-01T00:00:00Z',
      resultsAnnouncement: '2026-11-05T18:00:00Z',
    },
    guidelines: {
      maxFileSizeMB: 30,
      allowedFormats: ['JPG', 'JPEG', 'PNG'],
      minResolution: '2500 x 1800 px',
      maxSubmissionsPerUser: 1,
      rules: [
        'Strictly 1 submission per photographer.',
        'Street portraits, architectural perspectives, and documentary candids are accepted.',
        'High contrast black & white and dynamic color grading permitted.',
      ],
      eligibility: ['Open worldwide to all creators.'],
    },
    criteria: DEFAULT_SCORING_CRITERIA,
    submissionCount: 890,
    judgeIds: ['jdg-marcus-vance'],
    featured: true,
  },
  {
    id: 'comp-portrait-masters-2026',
    tenantId: 'tenant-pixel-prize',
    tenantName: 'Pixel-Prize Official',
    tenantLogo: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=150&q=80',
    title: 'Portrait Masters Invitational 2026',
    slug: 'portrait-masters-2026',
    category: 'Portrait & People',
    shortDescription: 'Capturing the depth of human expression, evocative lighting, character, and soul.',
    description: 'Celebrating the profound connection between photographer and subject. This contest honors emotional intimacy, studio mastery, and cultural storytelling.',
    coverImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80',
    status: 'judging',
    prizePool: '$12,000 USD',
    totalPrizeValue: 12000,
    prizes: [
      {
        rank: '1st_place',
        title: 'Master of Light Trophy',
        cashAmount: 7000,
        perks: ['Profoto Studio Lighting Kit ($3,000 value)', 'Front Cover Feature in Portrait Quarterly'],
      },
      {
        rank: '2nd_place',
        title: 'Portrait Excellence Silver',
        cashAmount: 3500,
        perks: ['Editorial spread', 'Silver Trophy'],
      },
      {
        rank: '3rd_place',
        title: 'Bronze Finalist',
        cashAmount: 1500,
        perks: ['Certificate of Excellence'],
      },
    ],
    timeline: {
      registrationOpen: '2026-05-01T00:00:00Z',
      submissionDeadline: '2026-08-01T23:59:59Z',
      aiEvaluationComplete: '2026-08-05T00:00:00Z',
      judgingDeadline: '2026-08-20T00:00:00Z',
      resultsAnnouncement: '2026-08-25T18:00:00Z',
    },
    guidelines: {
      maxFileSizeMB: 40,
      allowedFormats: ['JPG', 'TIFF', 'PNG'],
      minResolution: '3000 x 2000 px',
      maxSubmissionsPerUser: 1,
      rules: ['Subject consent model releases required if requested.', '1 entry per participant.'],
      eligibility: ['Open worldwide.'],
    },
    criteria: DEFAULT_SCORING_CRITERIA,
    submissionCount: 1650,
    judgeIds: ['jdg-sofia-chen'],
    featured: false,
  },
  {
    id: 'comp-nature-lens-2026',
    tenantId: 'tenant-nat-photo-club',
    tenantName: 'National Photography Club',
    tenantLogo: 'https://images.unsplash.com/photo-1502982720700-bfff97f2da6d?auto=format&fit=crop&w=150&q=80',
    title: 'Nature Through Your Lens: Annual Cup',
    slug: 'nature-through-your-lens-2026',
    category: 'Landscape & Nature',
    shortDescription: 'Epic mountains, mist-filled valleys, untouched coastlines, and pristine wilderness.',
    description: 'Honoring breathtaking landscape panoramas, macro botany, and the majestic serenity of untouched earthly environments.',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    status: 'results_published',
    prizePool: '$18,000 USD',
    totalPrizeValue: 18000,
    prizes: [
      {
        rank: '1st_place',
        title: 'Grand Nature Laureate',
        cashAmount: 10000,
        perks: ['National Park Expedition Grant', 'Grand Laureate Crystal Trophy'],
      },
      {
        rank: '2nd_place',
        title: 'Earth Vision Silver',
        cashAmount: 5000,
        perks: ['Hardcover Feature', 'Silver Medal'],
      },
      {
        rank: '3rd_place',
        title: 'Wilderness Bronze',
        cashAmount: 3000,
        perks: ['Bronze Medal', 'Pro platform pass'],
      },
    ],
    timeline: {
      registrationOpen: '2026-03-01T00:00:00Z',
      submissionDeadline: '2026-06-30T23:59:59Z',
      aiEvaluationComplete: '2026-07-05T00:00:00Z',
      judgingDeadline: '2026-07-20T00:00:00Z',
      resultsAnnouncement: '2026-07-25T18:00:00Z',
    },
    guidelines: {
      maxFileSizeMB: 50,
      allowedFormats: ['JPG', 'TIFF'],
      minResolution: '3840 x 2160 px (4K minimum)',
      maxSubmissionsPerUser: 1,
      rules: ['No composite sky replacements or artificial AI generation.'],
      eligibility: ['Open worldwide.'],
    },
    criteria: DEFAULT_SCORING_CRITERIA,
    submissionCount: 2240,
    judgeIds: ['jdg-elena-rostova'],
    featured: true,
  },
  {
    id: 'comp-monochrome-2026',
    tenantId: 'tenant-pixel-prize',
    tenantName: 'Pixel-Prize Official',
    tenantLogo: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=150&q=80',
    title: 'Monochrome Excellence Awards',
    slug: 'monochrome-excellence-2026',
    category: 'Monochrome & Black/White',
    shortDescription: 'Stripping away color to reveal pure emotion, deep shadows, and luminous tonal ranges.',
    description: 'A celebration of black and white photography where texture, tonal gradations, and shadow sculpt timeless visual poems.',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    status: 'upcoming',
    prizePool: '$8,000 USD',
    totalPrizeValue: 8000,
    prizes: [
      {
        rank: '1st_place',
        title: 'Silver Halide Master',
        cashAmount: 5000,
        perks: ['Custom Darkroom/Digital Print Set', 'Trophy'],
      },
      {
        rank: '2nd_place',
        title: 'Tonal Vision Award',
        cashAmount: 2000,
        perks: ['Monochrome Gallery spread'],
      },
      {
        rank: '3rd_place',
        title: 'Shadow & Light Finalist',
        cashAmount: 1000,
        perks: ['Honors certificate'],
      },
    ],
    timeline: {
      registrationOpen: '2026-09-01T00:00:00Z',
      submissionDeadline: '2026-12-01T23:59:59Z',
      aiEvaluationComplete: '2026-12-05T00:00:00Z',
      judgingDeadline: '2026-12-20T00:00:00Z',
      resultsAnnouncement: '2026-12-25T18:00:00Z',
    },
    guidelines: {
      maxFileSizeMB: 30,
      allowedFormats: ['JPG', 'PNG', 'TIFF'],
      minResolution: '2800 x 2000 px',
      maxSubmissionsPerUser: 1,
      rules: ['All images must be 100% grayscale or sepia toned.'],
      eligibility: ['Open worldwide.'],
    },
    criteria: DEFAULT_SCORING_CRITERIA,
    submissionCount: 0,
    judgeIds: ['jdg-marcus-vance'],
    featured: false,
  },
  {
    id: 'comp-aerial-2026',
    tenantId: 'tenant-nat-photo-club',
    tenantName: 'National Photography Club',
    tenantLogo: 'https://images.unsplash.com/photo-1502982720700-bfff97f2da6d?auto=format&fit=crop&w=150&q=80',
    title: 'Aerial Perspectives Grand Prix',
    slug: 'aerial-perspectives-2026',
    category: 'Aerial & Drone',
    shortDescription: 'Bird’s-eye compositions, abstract geological patterns, and stunning top-down vistas.',
    description: 'Redefining horizons from the sky. Open to drone, helicopter, and aircraft photographers looking down at the intricate textures of our planet.',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    status: 'active',
    prizePool: '$11,000 USD',
    totalPrizeValue: 11000,
    prizes: [
      {
        rank: '1st_place',
        title: 'Skyward Grand Champion',
        cashAmount: 6500,
        perks: ['DJI Inspire 3 Pro Drone Combo', 'Grand Trophy'],
      },
      {
        rank: '2nd_place',
        title: 'Aerial Visionary',
        cashAmount: 3000,
        perks: ['Drone accessory pack', 'Silver Medal'],
      },
      {
        rank: '3rd_place',
        title: 'Altitude Finalist',
        cashAmount: 1500,
        perks: ['Certificate of Honor'],
      },
    ],
    timeline: {
      registrationOpen: '2026-06-15T00:00:00Z',
      submissionDeadline: '2026-10-31T23:59:59Z',
      aiEvaluationComplete: '2026-11-05T00:00:00Z',
      judgingDeadline: '2026-11-15T00:00:00Z',
      resultsAnnouncement: '2026-11-20T18:00:00Z',
    },
    guidelines: {
      maxFileSizeMB: 40,
      allowedFormats: ['JPG', 'DNG', 'TIFF'],
      minResolution: '4000 x 3000 px',
      maxSubmissionsPerUser: 1,
      rules: ['Drone flights must adhere to local aviation safety regulations.'],
      eligibility: ['Open worldwide.'],
    },
    criteria: DEFAULT_SCORING_CRITERIA,
    submissionCount: 640,
    judgeIds: ['jdg-david-karanja'],
    featured: false,
  },
];

export const MOCK_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-polar-monarch',
    competitionId: 'comp-wildlife-2026',
    competitionTitle: 'Wildlife Photography Awards 2026',
    tenantName: 'Global Wildlife Alliance',
    userId: 'usr-alex-rivera', // Submitted by current user! Enforces "Submission Already Made"
    photographerName: 'Alex Rivera',
    photographerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    photographerLocation: 'Svalbard, Norway',
    title: 'Monarch of the Arctic Drift',
    description: 'A solitary polar bear navigates thinning summer pack ice in Svalbard under the surreal midnight sun, highlighting the fragility of arctic ecosystems.',
    category: 'Wildlife & Animals',
    imageUrl: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?auto=format&fit=crop&w=1600&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?auto=format&fit=crop&w=600&q=80',
    submittedAt: '2026-07-12T14:30:00Z',
    status: 'shortlisted',
    exif: {
      camera: 'Sony Alpha 1',
      lens: 'Sony FE 400mm f/2.8 GM OSS + 1.4x Teleconverter',
      focalLength: '560mm',
      aperture: 'f/4.0',
      shutterSpeed: '1/2500s',
      iso: 200,
      location: 'Svalbard Archipelago, 80°N',
      captureDate: '2026-06-28',
    },
    aiEvaluation: {
      overallScore: 94.2,
      isShortlisted: true,
      rank: 3,
      status: 'completed',
      breakdown: {
        composition: 96,
        technicalQuality: 98,
        sharpness: 95,
        colorHarmony: 91,
        creativityEstimate: 91,
      },
      tags: ['Polar Bear', 'Arctic', 'Ice Floe', 'High Dynamic Range', 'Golden Hour'],
      analyzedAt: '2026-07-12T14:35:12Z',
    },
    judgeReviews: [
      {
        judgeId: 'jdg-elena-rostova',
        judgeName: 'Elena Rostova',
        judgeAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
        judgeTitle: 'Senior Juror & NatGeo Editor',
        reviewedAt: '2026-07-18T10:15:00Z',
        criterionScores: [
          { criterionId: 'crit-comp', criterionName: 'Composition & Framing', score: 24, maxScore: 25 },
          { criterionId: 'crit-creat', criterionName: 'Creativity & Originality', score: 23, maxScore: 25 },
          { criterionId: 'crit-tech', criterionName: 'Technical Quality & Sharpness', score: 20, maxScore: 20 },
          { criterionId: 'crit-theme', criterionName: 'Theme Relevance & Context', score: 20, maxScore: 20 },
          { criterionId: 'crit-emot', criterionName: 'Emotional Impact & Wow Factor', score: 9, maxScore: 10 },
        ],
        totalScore: 96,
        comments: 'Breathtaking exposure control against snow and ice. The eye contact through the mist evokes an immediate, urgent conservation dialogue. Exceptional sharpness on the fur textures.',
      },
    ],
    finalJudgeScore: 96.0,
    likesCount: 342,
    viewsCount: 1890,
  },
  {
    id: 'sub-savannah-dawn',
    competitionId: 'comp-wildlife-2026',
    competitionTitle: 'Wildlife Photography Awards 2026',
    tenantName: 'Global Wildlife Alliance',
    userId: 'usr-charlotte-m',
    photographerName: 'Charlotte Moreau',
    photographerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    photographerLocation: 'Nairobi, Kenya',
    title: 'Echoes of the Mara',
    description: 'A lioness pauses atop a granite kopje as dawn mist rolls across the Maasai Mara savannah.',
    category: 'Wildlife & Animals',
    imageUrl: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=1600&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=600&q=80',
    submittedAt: '2026-07-10T09:20:00Z',
    status: 'shortlisted',
    exif: {
      camera: 'Canon EOS R5',
      lens: 'RF 600mm f/4L IS USM',
      focalLength: '600mm',
      aperture: 'f/4.5',
      shutterSpeed: '1/1600s',
      iso: 400,
      location: 'Maasai Mara, Kenya',
      captureDate: '2026-06-14',
    },
    aiEvaluation: {
      overallScore: 91.8,
      isShortlisted: true,
      rank: 7,
      status: 'completed',
      breakdown: {
        composition: 93,
        technicalQuality: 94,
        sharpness: 92,
        colorHarmony: 89,
        creativityEstimate: 90,
      },
      tags: ['Lioness', 'Savannah', 'Sunrise', 'Golden Rim Light'],
      analyzedAt: '2026-07-10T09:24:00Z',
    },
    judgeReviews: [],
    likesCount: 289,
    viewsCount: 1420,
  },
  {
    id: 'sub-emerald-falls',
    competitionId: 'comp-nature-lens-2026',
    competitionTitle: 'Nature Through Your Lens: Annual Cup',
    tenantName: 'National Photography Club',
    userId: 'usr-kenji-sato',
    photographerName: 'Kenji Sato',
    photographerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    photographerLocation: 'Nagano, Japan',
    title: 'Emerald Cascade Sanctuary',
    description: 'Silken waters rushing through ancient mossy volcanic boulders during spring melt in northern Japan.',
    category: 'Landscape & Nature',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    submittedAt: '2026-05-18T11:00:00Z',
    status: 'winner',
    winnerRank: '1st_place',
    finalRank: 1,
    finalJudgeScore: 98.5,
    exif: {
      camera: 'Nikon Z9',
      lens: 'NIKKOR Z 14-24mm f/2.8 S',
      focalLength: '18mm',
      aperture: 'f/11',
      shutterSpeed: '1.5s',
      iso: 64,
      location: 'Nagano Prefecture, Japan',
      captureDate: '2026-05-02',
    },
    aiEvaluation: {
      overallScore: 97.4,
      isShortlisted: true,
      rank: 1,
      status: 'completed',
      breakdown: {
        composition: 99,
        technicalQuality: 98,
        sharpness: 97,
        colorHarmony: 98,
        creativityEstimate: 95,
      },
      tags: ['Waterfall', 'Long Exposure', 'Lush Forest', 'High Tonal Range'],
      analyzedAt: '2026-05-18T11:04:00Z',
    },
    judgeReviews: [
      {
        judgeId: 'jdg-elena-rostova',
        judgeName: 'Elena Rostova',
        judgeAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
        judgeTitle: 'Senior Juror & NatGeo Editor',
        reviewedAt: '2026-07-15T14:00:00Z',
        criterionScores: [
          { criterionId: 'crit-comp', criterionName: 'Composition & Framing', score: 25, maxScore: 25 },
          { criterionId: 'crit-creat', criterionName: 'Creativity & Originality', score: 24, maxScore: 25 },
          { criterionId: 'crit-tech', criterionName: 'Technical Quality & Sharpness', score: 20, maxScore: 20 },
          { criterionId: 'crit-theme', criterionName: 'Theme Relevance & Context', score: 20, maxScore: 20 },
          { criterionId: 'crit-emot', criterionName: 'Emotional Impact & Wow Factor', score: 10, maxScore: 10 },
        ],
        totalScore: 99,
        comments: 'Pure poetry in motion. The silky water contrasts impeccably with the razor-sharp moss textures. Flawless dynamic range retention in the highlights.',
      },
    ],
    likesCount: 1250,
    viewsCount: 6800,
  },
  {
    id: 'sub-tokyo-rain',
    competitionId: 'comp-urban-stories-2026',
    competitionTitle: 'Urban Stories & Street Challenge',
    tenantName: 'Creative Lens Society',
    userId: 'usr-maya-lin',
    photographerName: 'Maya Lin',
    photographerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    photographerLocation: 'Tokyo, Japan',
    title: 'Neon Umbrella Reverie',
    description: 'Reflections of Shinjuku neon signs shimmering across wet asphalt under a transparent umbrella.',
    category: 'Urban & Architecture',
    imageUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1600&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=600&q=80',
    submittedAt: '2026-07-20T19:40:00Z',
    status: 'judge_review',
    exif: {
      camera: 'Leica Q2',
      lens: 'Summilux 28mm f/1.7 ASPH',
      focalLength: '28mm',
      aperture: 'f/1.7',
      shutterSpeed: '1/250s',
      iso: 800,
      location: 'Shinjuku, Tokyo',
      captureDate: '2026-07-15',
    },
    aiEvaluation: {
      overallScore: 92.5,
      isShortlisted: true,
      rank: 4,
      status: 'completed',
      breakdown: {
        composition: 94,
        technicalQuality: 92,
        sharpness: 90,
        colorHarmony: 96,
        creativityEstimate: 90,
      },
      tags: ['Cyberpunk', 'Rain', 'Neon', 'Street Candid', 'Reflections'],
      analyzedAt: '2026-07-20T19:44:00Z',
    },
    judgeReviews: [],
    likesCount: 512,
    viewsCount: 2310,
  },
  {
    id: 'sub-gaze-of-elders',
    competitionId: 'comp-portrait-masters-2026',
    competitionTitle: 'Portrait Masters Invitational 2026',
    tenantName: 'Pixel-Prize Official',
    userId: 'usr-samir-khan',
    photographerName: 'Samir Khan',
    photographerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    photographerLocation: 'Jaipur, India',
    title: 'Wisdom in the Lines',
    description: 'An intimate portrait of an 86-year-old Rajasthani turbanned elder illuminated by natural side-window illumination.',
    category: 'Portrait & People',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1600&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    submittedAt: '2026-06-25T15:10:00Z',
    status: 'shortlisted',
    exif: {
      camera: 'Fujifilm GFX 100 II',
      lens: 'GF 110mm f/2 R LM WR',
      focalLength: '110mm',
      aperture: 'f/2.0',
      shutterSpeed: '1/400s',
      iso: 160,
      location: 'Jaipur, Rajasthan',
      captureDate: '2026-06-10',
    },
    aiEvaluation: {
      overallScore: 95.1,
      isShortlisted: true,
      rank: 2,
      status: 'completed',
      breakdown: {
        composition: 96,
        technicalQuality: 97,
        sharpness: 98,
        colorHarmony: 93,
        creativityEstimate: 92,
      },
      tags: ['Medium Format', 'Elderly Portrait', 'Cultural Heritage', 'Chiaroscuro'],
      analyzedAt: '2026-06-25T15:14:00Z',
    },
    judgeReviews: [
      {
        judgeId: 'jdg-sofia-chen',
        judgeName: 'Sofia Chen',
        judgeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
        judgeTitle: 'Fashion & Fine Art Director',
        reviewedAt: '2026-08-03T16:20:00Z',
        criterionScores: [
          { criterionId: 'crit-comp', criterionName: 'Composition & Framing', score: 25, maxScore: 25 },
          { criterionId: 'crit-creat', criterionName: 'Creativity & Originality', score: 24, maxScore: 25 },
          { criterionId: 'crit-tech', criterionName: 'Technical Quality & Sharpness', score: 20, maxScore: 20 },
          { criterionId: 'crit-theme', criterionName: 'Theme Relevance & Context', score: 20, maxScore: 20 },
          { criterionId: 'crit-emot', criterionName: 'Emotional Impact & Wow Factor', score: 10, maxScore: 10 },
        ],
        totalScore: 99,
        comments: 'Stunning medium format depth. The light caressing the weathered contours of the subject’s face tells an entire generation of stories without uttering a word.',
      },
    ],
    likesCount: 680,
    viewsCount: 3100,
  },
  {
    id: 'sub-aerial-salt-flats',
    competitionId: 'comp-nature-lens-2026',
    competitionTitle: 'Nature Through Your Lens: Annual Cup',
    tenantName: 'National Photography Club',
    userId: 'usr-isabella-rossi',
    photographerName: 'Isabella Rossi',
    photographerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    photographerLocation: 'Uyuni, Bolivia',
    title: 'Mirror of the Cosmos',
    description: 'A razor-thin water film over the Salar de Uyuni reflecting twilight stars and Milky Way ribbon.',
    category: 'Landscape & Nature',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    submittedAt: '2026-05-20T03:30:00Z',
    status: 'winner',
    winnerRank: '2nd_place',
    finalRank: 2,
    finalJudgeScore: 96.2,
    exif: {
      camera: 'Sony Alpha 7R V',
      lens: 'Sony FE 14mm f/1.8 GM',
      focalLength: '14mm',
      aperture: 'f/1.8',
      shutterSpeed: '20s',
      iso: 3200,
      location: 'Salar de Uyuni, Bolivia',
      captureDate: '2026-04-19',
    },
    aiEvaluation: {
      overallScore: 95.8,
      isShortlisted: true,
      rank: 2,
      status: 'completed',
      breakdown: {
        composition: 97,
        technicalQuality: 96,
        sharpness: 94,
        colorHarmony: 98,
        creativityEstimate: 94,
      },
      tags: ['Astrophotography', 'Milky Way', 'Salt Flats', 'Reflection'],
      analyzedAt: '2026-05-20T03:35:00Z',
    },
    judgeReviews: [],
    likesCount: 940,
    viewsCount: 4500,
  },
  {
    id: 'sub-desert-dune-shadow',
    competitionId: 'comp-nature-lens-2026',
    competitionTitle: 'Nature Through Your Lens: Annual Cup',
    tenantName: 'National Photography Club',
    userId: 'usr-tariq-al-mansoor',
    photographerName: 'Tariq Al-Mansoor',
    photographerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    photographerLocation: 'Rub al Khali, Oman',
    title: 'Sinusoidal Dunes at Twilight',
    description: 'Razor-edged wind patterns sculpted into the crimson sands of the Empty Quarter under fading sunset.',
    category: 'Landscape & Nature',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    submittedAt: '2026-05-22T18:15:00Z',
    status: 'winner',
    winnerRank: '3rd_place',
    finalRank: 3,
    finalJudgeScore: 94.8,
    exif: {
      camera: 'Nikon Z7 II',
      lens: 'NIKKOR Z 24-70mm f/2.8 S',
      focalLength: '52mm',
      aperture: 'f/8.0',
      shutterSpeed: '1/60s',
      iso: 100,
      location: 'Empty Quarter, Oman',
      captureDate: '2026-05-09',
    },
    aiEvaluation: {
      overallScore: 93.6,
      isShortlisted: true,
      rank: 3,
      status: 'completed',
      breakdown: {
        composition: 95,
        technicalQuality: 94,
        sharpness: 93,
        colorHarmony: 96,
        creativityEstimate: 90,
      },
      tags: ['Sand Dunes', 'Golden Hour', 'Shadows', 'Minimalism'],
      analyzedAt: '2026-05-22T18:20:00Z',
    },
    judgeReviews: [],
    likesCount: 710,
    viewsCount: 3890,
  },
];

export const MOCK_WINNERS: WinnerRecord[] = [
  {
    id: 'win-nature-2026-1',
    submissionId: 'sub-emerald-falls',
    competitionId: 'comp-nature-lens-2026',
    competitionTitle: 'Nature Through Your Lens: Annual Cup',
    competitionCategory: 'Landscape & Nature',
    rank: '1st_place',
    rankTitle: 'Grand Nature Laureate',
    photoTitle: 'Emerald Cascade Sanctuary',
    photoUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80',
    photographerName: 'Kenji Sato',
    photographerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    photographerLocation: 'Nagano, Japan',
    finalScore: 98.5,
    aiScore: 97.4,
    prizeAmount: '$10,000 USD',
    year: 2026,
    quote: 'To capture the silence within the rush of moving water requires waiting for the exact whisper of light between dawn and morning mist.',
    exif: {
      camera: 'Nikon Z9',
      lens: 'NIKKOR Z 14-24mm f/2.8 S',
      focalLength: '18mm',
      aperture: 'f/11',
      shutterSpeed: '1.5s',
      iso: 64,
      location: 'Nagano Prefecture, Japan',
    },
  },
  {
    id: 'win-nature-2026-2',
    submissionId: 'sub-aerial-salt-flats',
    competitionId: 'comp-nature-lens-2026',
    competitionTitle: 'Nature Through Your Lens: Annual Cup',
    competitionCategory: 'Landscape & Nature',
    rank: '2nd_place',
    rankTitle: 'Earth Vision Silver',
    photoTitle: 'Mirror of the Cosmos',
    photoUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80',
    photographerName: 'Isabella Rossi',
    photographerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    photographerLocation: 'Uyuni, Bolivia',
    finalScore: 96.2,
    aiScore: 95.8,
    prizeAmount: '$5,000 USD',
    year: 2026,
    quote: 'Standing in the dead of night between the terrestrial salt and the celestial stars felt like floating in infinite space.',
    exif: {
      camera: 'Sony Alpha 7R V',
      lens: 'Sony FE 14mm f/1.8 GM',
      focalLength: '14mm',
      aperture: 'f/1.8',
      shutterSpeed: '20s',
      iso: 3200,
      location: 'Salar de Uyuni, Bolivia',
    },
  },
  {
    id: 'win-nature-2026-3',
    submissionId: 'sub-desert-dune-shadow',
    competitionId: 'comp-nature-lens-2026',
    competitionTitle: 'Nature Through Your Lens: Annual Cup',
    competitionCategory: 'Landscape & Nature',
    rank: '3rd_place',
    rankTitle: 'Wilderness Bronze Finalist',
    photoTitle: 'Sinusoidal Dunes at Twilight',
    photoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80',
    photographerName: 'Tariq Al-Mansoor',
    photographerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    photographerLocation: 'Rub al Khali, Oman',
    finalScore: 94.8,
    aiScore: 93.6,
    prizeAmount: '$3,000 USD',
    year: 2026,
    quote: 'The desert is never still. Every gust of wind redraws the geometry of eternity.',
    exif: {
      camera: 'Nikon Z7 II',
      lens: 'NIKKOR Z 24-70mm f/2.8 S',
      focalLength: '52mm',
      aperture: 'f/8.0',
      shutterSpeed: '1/60s',
      iso: 100,
      location: 'Empty Quarter, Oman',
    },
  },
];

export const MOCK_GALLERY_PHOTOS: Photo[] = [
  {
    id: 'gal-1',
    title: 'Monarch of the Arctic Drift',
    photographerName: 'Alex Rivera',
    photographerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    competitionTitle: 'Wildlife Photography Awards 2026',
    competitionId: 'comp-wildlife-2026',
    imageUrl: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?auto=format&fit=crop&w=1200&q=80',
    category: 'Wildlife & Animals',
    likes: 342,
    views: 1890,
    award: 'AI Shortlist Rank #3',
    description: 'Polar bear navigating arctic pack ice under midnight sun in Svalbard.',
    exif: {
      camera: 'Sony Alpha 1',
      lens: 'Sony FE 400mm f/2.8 GM',
      focalLength: '560mm',
      aperture: 'f/4.0',
      shutterSpeed: '1/2500s',
      iso: 200,
      location: 'Svalbard, Norway',
    },
  },
  {
    id: 'gal-2',
    title: 'Emerald Cascade Sanctuary',
    photographerName: 'Kenji Sato',
    photographerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    competitionTitle: 'Nature Through Your Lens: Annual Cup',
    competitionId: 'comp-nature-lens-2026',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    category: 'Landscape & Nature',
    likes: 1250,
    views: 6800,
    award: '🥇 1st Place Winner',
    description: 'Silken cascade rushing through volcanic moss beds in spring.',
    exif: {
      camera: 'Nikon Z9',
      lens: 'NIKKOR Z 14-24mm f/2.8 S',
      focalLength: '18mm',
      aperture: 'f/11',
      shutterSpeed: '1.5s',
      iso: 64,
      location: 'Nagano, Japan',
    },
  },
  {
    id: 'gal-3',
    title: 'Neon Umbrella Reverie',
    photographerName: 'Maya Lin',
    photographerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    competitionTitle: 'Urban Stories Challenge',
    competitionId: 'comp-urban-stories-2026',
    imageUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1200&q=80',
    category: 'Urban & Architecture',
    likes: 512,
    views: 2310,
    award: 'AI Shortlist Rank #4',
    description: 'Shinjuku neon reflections glistening on rain-slicked asphalt.',
    exif: {
      camera: 'Leica Q2',
      lens: 'Summilux 28mm f/1.7',
      focalLength: '28mm',
      aperture: 'f/1.7',
      shutterSpeed: '1/250s',
      iso: 800,
      location: 'Tokyo, Japan',
    },
  },
  {
    id: 'gal-4',
    title: 'Wisdom in the Lines',
    photographerName: 'Samir Khan',
    photographerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    competitionTitle: 'Portrait Masters 2026',
    competitionId: 'comp-portrait-masters-2026',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80',
    category: 'Portrait & People',
    likes: 680,
    views: 3100,
    award: 'Judge Score: 99.0',
    description: 'Natural light portrait of an 86-year-old Rajasthani elder.',
    exif: {
      camera: 'Fujifilm GFX 100 II',
      lens: 'GF 110mm f/2 R LM WR',
      focalLength: '110mm',
      aperture: 'f/2.0',
      shutterSpeed: '1/400s',
      iso: 160,
      location: 'Jaipur, India',
    },
  },
  {
    id: 'gal-5',
    title: 'Echoes of the Mara',
    photographerName: 'Charlotte Moreau',
    photographerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    competitionTitle: 'Wildlife Photography Awards 2026',
    competitionId: 'comp-wildlife-2026',
    imageUrl: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=1200&q=80',
    category: 'Wildlife & Animals',
    likes: 289,
    views: 1420,
    award: 'AI Shortlist Rank #7',
    description: 'Lioness surveying the golden savannah at dawn atop a granite kopje.',
    exif: {
      camera: 'Canon EOS R5',
      lens: 'RF 600mm f/4L IS USM',
      focalLength: '600mm',
      aperture: 'f/4.5',
      shutterSpeed: '1/1600s',
      iso: 400,
      location: 'Maasai Mara, Kenya',
    },
  },
  {
    id: 'gal-6',
    title: 'Mirror of the Cosmos',
    photographerName: 'Isabella Rossi',
    photographerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    competitionTitle: 'Nature Through Your Lens: Annual Cup',
    competitionId: 'comp-nature-lens-2026',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    category: 'Landscape & Nature',
    likes: 940,
    views: 4500,
    award: '🥈 2nd Place Winner',
    description: 'Salar de Uyuni salt flat reflecting stars in nocturnal stillness.',
    exif: {
      camera: 'Sony Alpha 7R V',
      lens: 'Sony FE 14mm f/1.8 GM',
      focalLength: '14mm',
      aperture: 'f/1.8',
      shutterSpeed: '20s',
      iso: 3200,
      location: 'Uyuni, Bolivia',
    },
  },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: 'art-composition-rules',
    slug: 'mastering-composition-visual-tension',
    title: 'Mastering Composition: Beyond the Rule of Thirds to Create Visual Tension',
    excerpt: 'Discover dynamic symmetry, negative space balancing, and leading lines that captivate contest jury panels.',
    coverImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80',
    category: 'Composition Tips',
    author: {
      name: 'Elena Rostova',
      role: 'Master Juror & NatGeo Editor',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    },
    publishedAt: '2026-07-28',
    readTime: '6 min read',
    featured: true,
    tags: ['Composition', 'Judging Tips', 'Visual Storytelling'],
    content: `When analyzing thousands of competition submissions, jurors can immediately distinguish between a photographer who relies mechanically on standard grid overlays and an artist who understands dynamic tension.

### 1. The Power of Intentional Asymmetry
While the rule of thirds provides an initial safety net, extraordinary photographs frequently leverage intentional weight imbalance. Placing high-contrast focal subjects against vast expanses of low-frequency negative space pulls the viewer's gaze with magnetic gravity.

### 2. Micro-Leading Lines
Leading lines do not need to be highway lanes or railroad tracks. Look for subtle organic gradients:
- The curve of a dune shadow falling at sunset
- A predator's gaze directed off-frame toward unseen prey
- Light falloff across damp cobblestones

### 3. Edge Patrol
Before clicking the shutter, scan the extreme four corners of your viewfinder. Extraneous twigs, clipped pedestrian limbs, or blown-out background highlights degrade otherwise breathtaking compositions.`,
  },
  {
    id: 'art-wildlife-ethics',
    slug: 'ethical-wildlife-photography-field-guide',
    title: 'The Field Guide to Ethical Wildlife Photography in Extreme Habitats',
    excerpt: 'How to capture intimate, award-winning behavioral moments without distressing endangered species or disrupting habitats.',
    coverImage: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?auto=format&fit=crop&w=1200&q=80',
    category: 'Wildlife Photography',
    author: {
      name: 'David Karanja',
      role: 'Conservation Photographer',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    },
    publishedAt: '2026-07-15',
    readTime: '8 min read',
    featured: false,
    tags: ['Wildlife', 'Conservation', 'Telephoto Gear', 'Fieldcraft'],
    content: `Great wildlife photography is born of patience, stealth, and unwavering respect for animal autonomy. In prestigious competitions like the Wildlife Photography Awards, ethical integrity is non-negotiable.

### Respecting Critical Flight Distances
Every species possesses a biological comfort threshold. When an animal alters its natural behavior—ceasing foraging, fixing rigid eyes upon you, or shifting posture defensively—you have breached that threshold.

### The Advantage of Super-Telephoto Focal Lengths
Modern optical technology allows photographers to capture raw facial emotion from safe distances:
- Use 400mm to 800mm equivalent focal lengths.
- Employ silent electronic shutters to avoid startling sensitive birds and mammals.
- Never use playback calls or baiting tactics.`,
  },
  {
    id: 'art-portrait-lighting',
    slug: 'sculpting-dimension-with-portrait-lighting',
    title: 'Sculpting Dimension: Chiaroscuro & Cinematic Light in Modern Portraiture',
    excerpt: 'Step-by-step studio setups and natural light feathering methods for unforgettable character portraits.',
    coverImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80',
    category: 'Portrait Lighting',
    author: {
      name: 'Sofia Chen',
      role: 'Fashion & Fine Art Director',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    },
    publishedAt: '2026-06-30',
    readTime: '5 min read',
    featured: false,
    tags: ['Portraiture', 'Studio Lighting', 'Chiaroscuro', 'Color Grading'],
    content: `Light does not merely illuminate a subject; it reveals their emotional psychological architecture. In competition judging, portraits that exhibit three-dimensional depth and deliberate shadow transitions always stand above flatly lit captures.`,
  },
  {
    id: 'art-street-timing',
    slug: 'the-decisive-millisecond-in-street-photography',
    title: 'The Decisive Millisecond: Anticipating Candid Geometry in the Street',
    excerpt: 'Mastering zone focusing, pre-visualization, and architectural frame traps in bustling metropolises.',
    coverImage: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1200&q=80',
    category: 'Street Photography',
    author: {
      name: 'Marcus Vance',
      role: 'Architectural & Street Juror',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    },
    publishedAt: '2026-06-18',
    readTime: '7 min read',
    featured: false,
    tags: ['Street Candid', 'Leica', 'Urban Architecture', 'Monochrome'],
    content: `Street photography is the art of waiting for chaos to align into momentary order. By setting an architectural frame trap—a slice of morning light between skyscrapers—you wait for the human element to step into the stage.`,
  },
  {
    id: 'art-raw-workflow',
    slug: 'pro-color-grading-and-dynamic-range-mastery',
    title: 'From RAW to Podium: Ethical Color Grading and Dynamic Range Mastery',
    excerpt: 'How to process high-dynamic range RAW files without triggering AI artifact disqualification flags.',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    category: 'Editing Guides',
    author: {
      name: 'Kenji Sato',
      role: 'Grand Nature Laureate',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    },
    publishedAt: '2026-05-28',
    readTime: '9 min read',
    featured: false,
    tags: ['RAW Processing', 'Lightroom', 'Dynamic Range', 'Color Science'],
    content: `Our AI evaluation system measures pixel tonal distribution and edge halos to detect over-sharpening or unnatural tone mapping. Learn how to maintain organic film-like tonality while expanding dynamic range.`,
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'usr-alex-rivera',
    title: 'Submission Shortlisted! ⭐',
    message: 'Your photograph "Monarch of the Arctic Drift" scored 94.2 and has been shortlisted for jury evaluation in the Wildlife Photography Awards 2026.',
    type: 'ai_review',
    read: false,
    timestamp: '2026-07-12T14:40:00Z',
    link: '/dashboard/submissions/sub-polar-monarch',
  },
  {
    id: 'notif-2',
    userId: 'usr-alex-rivera',
    title: 'Juror Feedback Received',
    message: 'Elena Rostova submitted a 96/100 score and written review for "Monarch of the Arctic Drift".',
    type: 'judging',
    read: false,
    timestamp: '2026-07-18T10:20:00Z',
    link: '/dashboard/submissions/sub-polar-monarch',
  },
  {
    id: 'notif-3',
    userId: 'usr-alex-rivera',
    title: 'Competition Deadline Alert ⏳',
    message: 'Urban Stories Challenge closes for submissions in 65 days. Make sure to finalize your entry.',
    type: 'deadline',
    read: true,
    timestamp: '2026-08-01T09:00:00Z',
    link: '/competitions/comp-urban-stories-2026',
  },
  {
    id: 'notif-4',
    userId: 'usr-alex-rivera',
    title: 'Nature Cup Winners Announced 🏆',
    message: 'Official results for Nature Through Your Lens have been published in the Hall of Fame.',
    type: 'award',
    read: true,
    timestamp: '2026-07-25T19:00:00Z',
    link: '/winners',
  },
];

export const MOCK_ADMIN_STATS = {
  totalUsers: 14820,
  activeCompetitions: 4,
  totalSubmissions: 38450,
  pendingJudging: 128,
  publishedWinners: 42,
  totalPrizeDistributed: '$145,000 USD',
  submissionGrowth: [
    { month: 'Jan', count: 2400 },
    { month: 'Feb', count: 3100 },
    { month: 'Mar', count: 4200 },
    { month: 'Apr', count: 5600 },
    { month: 'May', count: 7100 },
    { month: 'Jun', count: 8900 },
    { month: 'Jul', count: 7150 },
  ],
  categoryDistribution: [
    { category: 'Wildlife & Animals', percentage: 34, count: 13070 },
    { category: 'Landscape & Nature', percentage: 28, count: 10760 },
    { category: 'Portrait & People', percentage: 18, count: 6920 },
    { category: 'Urban & Street', percentage: 12, count: 4610 },
    { category: 'Aerial & Drone', percentage: 8, count: 3090 },
  ],
  recentActivities: [
    {
      id: 'act-1',
      actor: 'Elena Rostova',
      actorRole: 'Judge',
      action: 'completed scoring for submission',
      target: 'Monarch of the Arctic Drift',
      timestamp: '15 minutes ago',
    },
    {
      id: 'act-2',
      actor: 'AI Evaluation Engine',
      actorRole: 'System',
      action: 'shortlisted 14 entries in',
      target: 'Wildlife Photography Awards',
      timestamp: '1 hour ago',
    },
    {
      id: 'act-3',
      actor: 'Charlotte Moreau',
      actorRole: 'Photographer',
      action: 'submitted a new photograph to',
      target: 'Urban Stories Challenge',
      timestamp: '3 hours ago',
    },
    {
      id: 'act-4',
      actor: 'Creative Lens Society',
      actorRole: 'Tenant Admin',
      action: 'updated prize distribution for',
      target: 'Monochrome Excellence Awards',
      timestamp: '5 hours ago',
    },
  ],
};
